Mytest/Mytest/urls.py
from django.conf.urls import url
from django.contrib import admin
from web01.views import main,common

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^login/', common.Login.as_view()),
    url(r'^logout/', common.logout),
    url(r'^adduser/$', main.adduser),
    url(r'^host_group/$', main.Host_group.as_view()),
    url(r'^idc/$', main.Idc.as_view()),
    url(r'^host/$', main.Host.as_view()),
    url(r'^user/$', main.User.as_view()),
    url(r'^log/$', main.Log.as_view()),
    url(r'^add_host/$', main.Add_host.as_view()),
    url(r'^host/details/(?P<id>\d+)', main.HostDetails.as_view()),
    # url(r'^test/', main.test),
]

Mytest/web01/models.py
from django.db import models
import django.utils.timezone as timezone
# Create your models here.



from django.contrib.auth.models import AbstractUser
class UserInfo(AbstractUser):
    """堡垒机账号"""
    nid = models.AutoField(primary_key=True)
    telephone = models.CharField(max_length=11, null=True, unique=True)
    create_time = models.DateTimeField(verbose_name='创建时间', auto_now_add=True)
    def __str__(self):
        return self.username




class Host_group(models.Model):
    nid = models.AutoField(primary_key=True)
    group_name = models.CharField(max_length=32,unique=True)

    def __str__(self):
        return self.group_name

class IDC(models.Model):
    nid = models.AutoField(primary_key=True)
    idc = models.CharField(max_length=32)
    def __str__(self):
        return self.idc

class Host(models.Model):
    """存储主机列表"""
    host_name = models.CharField(max_length=64)
    in_ip = models.GenericIPAddressField(unique=True)		# 内IP
    out_ip = models.GenericIPAddressField(null=False)		# 外IP
    port = models.SmallIntegerField(default=22)				# 端口
    host_user = models.CharField(max_length=32)				# 主机用户
    password = models.CharField(max_length=32)	            # 密码
    idc = models.ForeignKey("IDC")							# 机房
    Host_group = models.ForeignKey("Host_group")	        # 主机组
    user = models.ForeignKey("UserInfo",null=True)        # 主机分配的堡垒机账户
    def __str__(self):
        return self.host_name	                            # 返回主机名

class CommandIog(models.Model):
    nid = models.AutoField(primary_key=True)
    user = models.ForeignKey("UserInfo")
    host = models.ForeignKey("Host")
    command = models.CharField(max_length=128)
    date = models.DateTimeField('保存日期',default = timezone.now)


# nid = models.AutoField(primary_key=True)
# user = models.ForeignKey("UserInfo")
# host = models.ForeignKey("Host")
# command = models.CharField(max_length=128)
# date = models.DateTimeField('保存日期',default = timezone.now)





Mytest/web01/views/common.py
from django.shortcuts import render, redirect,HttpResponse
from django.contrib import auth
from  django.views import View
from django import forms
from django.forms import widgets
from web01 import models
from django.core.exceptions import ValidationError
from django.contrib.auth.decorators import login_required


class Login(View):
    def get(self,request):
        return render(request,'login2.html')

    def post(self,request):
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = auth.authenticate(request,username=username,password=password)
        print(user)
        if user:
            print(user.username)
            auth.login(request,user)
            return redirect('/host/')
        else:
            return redirect('/login/')


from django.contrib.auth.decorators import login_required
@login_required
def logout(request):
    print('logout')
    auth.logout(request)
    return redirect('/login/')


class RegForms(forms.Form):
    name = forms.CharField(max_length=20, min_length=2, label='用户名',
                           widget=widgets.TextInput(attrs={'class': 'form-control'}),
                           error_messages={'max_length': '太长了', 'min_length': '太短了'}
                           )
    pwd = forms.CharField(max_length=20, min_length=2, label='密码',
                          widget=widgets.PasswordInput(attrs={'class': 'form-control'}),
                          error_messages={'max_length': '太长了', 'min_length': '太短了'}
                          )
    re_pwd = forms.CharField(max_length=20, min_length=2, label='确认密码',
                             widget=widgets.PasswordInput(attrs={'class': 'form-control'}),
                             error_messages={'max_length': '太长了', 'min_length': '太短了'}
                             )
    email = forms.EmailField(label='邮箱',
                             widget=widgets.EmailInput(attrs={'class': 'form-control'}),
                             )

    def clean_name(self):
        name = self.cleaned_data.get('name')
        user = models.UserInfo.objects.filter(username=name).first()
        if user:
            raise ValidationError('用户已经存在')
        else:
            return name

    def clean(self):
        pwd = self.cleaned_data.get('pwd')
        re_pwd = self.cleaned_data.get('re_pwd')
        if pwd == re_pwd:
            return self.cleaned_data
        else:
            # __all__
            raise ValidationError('两次密码不一致')

Mytest/templates/add_host.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="/static/Bootstrap_files/bootstrap.min.css">
    <script src="/static/jquery-3.2.1.min.js"></script>
    <style>
        .errors {
            color: red;
        }
    </style>
    <title>添加主机</title>
</head>
<body>
<div class="container-fluid">
    <div class="row">
        <div class="col-md-3 col-md-offset-4">
            <h1>添加主机</h1>
            <form action="/add_host/" method="POST">
                {% csrf_token %}
                <div class="form-group">
                    <label for="">主机名</label>
                    <input type="text" name="host_name" class="form-control">
                </div>
                <div class="form-group">
                    <label for="">内网IP</label>
                    <input type="text" name="in_ip" class="form-control">
                </div>
                <div class="form-group">
                    <label for="">外网IP，没有填(null)</label>
                    <input type="text" name="out_ip" class="form-control">
                </div>
                <div class="form-group">
                    <label for="">端口</label>
                    <input type="text" name="port" class="form-control">
                </div>
                <div class="form-group">
                    <label for="">主机用户</label>
                    <input type="text" name="host_user" class="form-control">
                </div>
                <div class="form-group">
                    <label for="">主机密码</label>
                    <input type="text" name="password" class="form-control">
                </div>

                <div class="form-group">
                    <label for="">机房</label>
                    <select name="idc">
                        {% for idc in idc_list %} }}
                            <option value="{{ idc.nid }}">{{ idc.idc }}</option>
                        {% endfor %}
                    </select>
                </div>
                <div class="form-group">
                    <label for="">主机组管理</label>
                    <select name="Host_group">
                        {% for host_group in host_group_list %} }}
                            <option value="{{ host_group.nid }}">{{ host_group.group_name }}</option>
                        {% endfor %}
                    </select>
                </div>
                <div class="form-group">
                    <label for="">用户人员管理</label>
                        <select name="user">
                            {% for user in user_list %} }}
                                <option value="{{ user.nid }}">{{ user.username }}</option>
                            {% endfor %}
                        </select>
                </div>
                <div class="modal-footer">
                    <input type="submit" value="确定" class="btn btn-default">
                    <a href="/host/">
                        <li class="btn  btn-primary">返回</li>
                    </a>
                </div>
            </form>

        </div>
    </div>
</div>

</body>
</html>

Mytest/templates/adduser.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="/static/Bootstrap_files/bootstrap.min.css">
    <script src="/static/jquery-3.2.1.min.js"></script>
    <style>
        .errors {
            color: red;
        }
    </style>
    <title>新增用户</title>
</head>
<body>
<div class="container-fluid">
    <div class="row">
        <div class="col-md-6 col-md-offset-3">
            <h1>新增用户</h1>
            <form id="my_form">

                {% csrf_token %}
                {% for foo in form_obj %}
                    <div class="form-group">
                        <label for="">{{ foo.label }}</label>
                        {{ foo }} <span class="errors"></span>
                    </div>
                {% endfor %}

                <div class="modal-footer">
                    <input type="button" id="id_button" class="btn btn-success" value="确定">
                    <a href="/user/">
                        <li class="btn btn-default">返回</li>
                    </a>
                </div>
            </form>

        </div>
    </div>
</div>

<script>


    $("#id_button").click(function () {
        var formdata = new FormData()
        var tt = $("#my_form").serializeArray()
        $.each(tt, function (index, value) {
            formdata.append(value.name, value.value)
        })
        console.log(tt)

        $.ajax({
            url: '',
            type: 'post',
            processData: false,
            contentType: false,
            data: formdata,
            success: function (data) {
                //console.log(data)
                if (data.user) {
                    location.href = '/user/'
                } else {
                    $.each(data.msg, function (index, value) {
                        console.log(index)
                        console.log(value)
                        if (index == "__all__") {
                            $("#id_re_pwd").next().text(value[0])
                        }
                        $("#id_" + index).next().text(value[0]).parent().addClass('has-error')
                    })
                    setTimeout(function () {
                        $(".form-group").removeClass('has-error')
                        $('span').text("")
                    }, 5000)
                }

            }

        })

    })
</script>
</body>
</html>

Mytest/templates/base.html
<!DOCTYPE html>
<html lang="zh-CN">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- 上述3个meta标签*必须*放在最前面，任何其他内容都*必须*跟随其后！ -->
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="https://v3.bootcss.com/favicon.ico">

    <title>MyJumpserver</title>

    <!-- Bootstrap core CSS -->
    <link href="/static/Bootstrap_files/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" href="/static/font-awesome/css/font-awesome.min.css">
    <!-- Custom styles for this template -->
    <link href="/static/Bootstrap_files/dashboard.css" rel="stylesheet">
    <style>
        .table-toolbar {
            margin-bottom: 15px;
        }
    </style>
</head>
<body>

<nav class="navbar navbar-inverse navbar-fixed-top">
    <div class="container-fluid">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar"
                    aria-expanded="false" aria-controls="navbar">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="#">MyJumpserver</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
            <ul class="nav navbar-nav navbar-right">
                <li><a href="#">Dashboard</a></li>
                <li><a href="#">Settings</a></li>
                <li><a href="#">Profile</a></li>
                <li><a href="#">{{ request.user }}</a></li>
            </ul>
            <form class="navbar-form navbar-right">
                <input type="text" class="form-control" placeholder="Search...">
            </form>
        </div>
    </div>
</nav>

<div class="container-fluid">
    <div class="row">
        <div class="col-sm-3 col-md-2 sidebar">
            <ul class="nav nav-sidebar">
                <li class="active"><a href="#">资产管理<span class="sr-only">(current)</span></a>
                </li>
                <li><a href="#">仪表盘</a></li>
                <li><a href="/idc/">机房管理</a></li>
                <li><a href="/host_group/">服务器组管理</a></li>
                <li><a href="#">用户组管理</a></li>
            </ul>
            <ul class="nav nav-sidebar">
                <li><a href="/host/">主机列表</a></li>
                <li><a href="/add_host/">新增主机</a></li>
                <li><a href="#">批量新增主机</a></li>
            </ul>
            <ul class="nav nav-sidebar">
                <li><a href="#">批量执行服务器命令</a></li>
                <li><a href="#">git发布代码</a></li>
                <li><a href="#">svn发布代码</a></li>
                <li><a href="/logout/">退出</a></li>
            </ul>
        </div>
        <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
            <h1 class="page-header">主机管理系统</h1>
            <!-- 面版开始 -->
            <div class="panel panel-primary">

                {% block panel_title %}
                {% endblock panel_title %}


                <div class="panel-body">
                    <!--表格 工具栏开始-->
                    {% block table %}

                    {% endblock table %}
                    <!--表格 工具栏结束-->
                    <!--分页开始-->
                    <div>
                        <nav aria-label="Page navigation" class="pull-right">
                            <ul class="pagination">
                                <li>
                                    <a href="#" aria-label="Previous">
                                        <span aria-hidden="true">&laquo;</span>
                                    </a>
                                </li>
                                <li><a href="#">1</a></li>
                                <li><a href="#">2</a></li>
                                <li><a href="#">3</a></li>
                                <li><a href="#">4</a></li>
                                <li><a href="#">5</a></li>
                                <li>
                                    <a href="#" aria-label="Next">
                                        <span aria-hidden="true">&raquo;</span>
                                    </a>
                                </li>
                            </ul>
                        </nav>
                    </div>
                    <!--分页结束-->
                </div>
            </div>
            <!-- 面版结束 -->
        </div>
    </div>
</div>



<!-- Bootstrap core JavaScript
================================================== -->
<!-- Placed at the end of the document so the pages load faster -->

{% block model %}
{% endblock model %}

{% block script %}
{% endblock script %}

</body>
</html>

Mytest/templates/base/base.html
<!DOCTYPE html>
<html lang="zh-CN">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- 上述3个meta标签*必须*放在最前面，任何其他内容都*必须*跟随其后！ -->
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="https://v3.bootcss.com/favicon.ico">

    <title>MyJumpserver</title>

    <!-- Bootstrap core CSS -->
    <link href="/static/Bootstrap_files/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" href="/static/font-awesome/css/font-awesome.min.css">
    <!-- Custom styles for this template -->
    <link href="/static/Bootstrap_files/dashboard.css" rel="stylesheet">
    <style>
        .table-toolbar {
            margin-bottom: 15px;
        }
    </style>
</head>
<body>

<nav class="navbar navbar-inverse navbar-fixed-top">
    <div class="container-fluid">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar"
                    aria-expanded="false" aria-controls="navbar">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="#">MyJumpserver</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
            <ul class="nav navbar-nav navbar-right">
                <li><a href="#">Dashboard</a></li>
                <li><a href="#">Settings</a></li>
                <li><a href="#">Profile</a></li>
                <li><a href="#">{{ request.user }}</a></li>
            </ul>
            <form class="navbar-form navbar-right">
                <input type="text" class="form-control" placeholder="Search...">
            </form>
        </div>
    </div>
</nav>

<div class="container-fluid">
    <div class="row">
        <div class="col-sm-3 col-md-2 sidebar">
            <ul class="nav nav-sidebar">
                <li class="active">
                    <a href="#">资产管理<span class="sr-only">(current)</span></a>
                </li>
                {% block super_href %}

                {% endblock super_href %}



            </ul>
            <ul class="nav nav-sidebar">
                <li><a href="/host/">主机列表</a></li>
                <li><a href="http://192.168.10.55:4200" target="_Blank">远程执行终端</a></li>
                <li><a href="#">批量执行服务器命令</a></li>
                <li><a href="#">git发布代码</a></li>
                <li><a href="#">svn发布代码</a></li>
                <li><a href="/logout/">退出</a></li>
            </ul>
        </div>
        <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
            <h1 class="page-header">主机管理系统</h1>
            <!-- 面版开始 -->
            <div class="panel panel-primary">

                {% block panel_title %}
                {% endblock panel_title %}


                <div class="panel-body">
                    <!--表格 工具栏开始-->
                    {% block table %}

                    {% endblock table %}
                    <!--表格 工具栏结束-->
                    <!--分页开始-->
                    <div>
                        <nav aria-label="Page navigation" class="pull-right">
                            <ul class="pagination">
                                <li>
                                    <a href="#" aria-label="Previous">
                                        <span aria-hidden="true">&laquo;</span>
                                    </a>
                                </li>
                                <li><a href="#">1</a></li>
                                <li><a href="#">2</a></li>
                                <li><a href="#">3</a></li>
                                <li><a href="#">4</a></li>
                                <li><a href="#">5</a></li>
                                <li>
                                    <a href="#" aria-label="Next">
                                        <span aria-hidden="true">&raquo;</span>
                                    </a>
                                </li>
                            </ul>
                        </nav>
                    </div>
                    <!--分页结束-->
                </div>
            </div>
            <!-- 面版结束 -->
        </div>
    </div>
</div>



<!-- Bootstrap core JavaScript
================================================== -->
<!-- Placed at the end of the document so the pages load faster -->

{% block model %}
{% endblock model %}


{% block script %}
{% endblock script %}


</body>
</html>

Mytest/templates/base/com_base.html
{% extends "base/base.html" %}

{% block super_href %}
    <li><a href="#">仪表盘</a></li>
    <li><a href="/idc/">机房管理</a></li>
    <li><a href="/host_group/">服务器组管理</a></li>
    <li><a href="/host_group/">用户组管理</a></li>
    <li><a href="/add_host/">新增主机</a></li>
    <li><a href="#">批量新增主机</a></li>
    <li><a href="/log/">操作日志查询</a></li>
{% endblock super_href %}


Mytest/templates/base/host_base.html
{% extends "base/com_base.html" %}


{% block panel_itle %}
    <div class="panel-heading">
        <h3 class="panel-title">主机管理</h3>
    </div>
{% endblock panel_itle %}

{% block table %}
    <!--表格 工具栏结束-->
    <div class="row table-toolbar">
        <div class="col-md-9">
            <div class="input-group">
                <td id="Search_ip">
                    <input type="text" class="form-control" placeholder="Search for ip...">
                    <span class="input-group-btn">
                        <button class="btn btn-default" type="button">Go!</button>
                    </span>
                </td>
                <td id="Search_type">
                    <input type="text" class="form-control" placeholder="Search for type...">
                    <span class="input-group-btn">
                        <button class="btn btn-default" type="button">Go!</button>
                    </span>
                </td>
                <td>
                    <input type="Search_idc" class="form-control" placeholder="Search for idc...">
                    <span class="input-group-btn">
                        <button class="btn btn-default" type="button">Go!</button>
                    </span>
                </td>
            </div>
        </div><!-- /.col-lg-6 -->
        {% block add_host %}
        {% endblock add_host %}
    </div>
    <table class="table table-striped table-bordered">
        <thead>
        <tr>
            <th>id</th>
            <th>主机名</th>
            <th>内网iP</th>
            <th>外网iP</th>
            <th>类型</th>
            <th>机房</th>
            <th>管理人员</th>
            <th>操作</th>
        </tr>
        </thead>
        <tbody id="tb">
        {% for host in host_list %}
            <tr nid="{{ host.id }}">
                {#                <td>{{ forloop.counter }}</td>#}
                <td na="nid">{{ host.id }}</td>
                <td na="host_name">{{ host.host_name }}</td>
                <td>{{ host.in_ip }}</td>
                <td>{{ host.out_ip }}</td>
                <td>{{ host.Host_group }}</td>
                <td>{{ host.idc }}</td>
                <td>{{ host.user }}</td>
                <td>
                    <a href="#">
                        <button class="btn btn-info btn-sm">
                            <i class="fa  fa-fw" aria-hidden="true"></i>连接
                        </button>
                    </a>
                    <a href="#">
                        <button class="btn btn-info btn-sm">
                            <i class="fa fa-pencil fa-fw" aria-hidden="true"></i>监控
                        </button>
                    </a>
                    {% block operation %}
                    {% endblock operation %}
                </td>
            </tr>
        {% endfor %}

        </tbody>
    </table>
{% endblock table %}


{% block model %}
    <div class="modal fade" id="delModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span
                            aria-hidden="true">&times;</span></button>
                    <h4 class="modal-title" id="myModalLabel">删除主机</h4>
                </div>
                <div class="modal-body">
                    <form id="fm" class="form-horizontal">
                        <input type="text" class="ni" name="nid" style="display: none"/>

                        <div class="form-group">
                            <label for="username" class="col-sm-2 control-label">姓名</label>
                            <div class="col-sm-10">
                                <input type="text" class="form-control" readOnly="true" name="user" placeholder="姓名">
                            </div>
                        </div>
                    </form>
                </div>
                <div class="modal-footer">
                    <span id="errorMsg" style="color: red;"></span>
                    <button type="button" class="btn btn-default" data-dismiss="modal">取消</button>
                    <button type="button" class="btn btn-primary" id="delConfirm">删除</button>
                </div>
            </div>
        </div>
    </div>
{% endblock model %}

Mytest/templates/base/user_host_base.html
{% extends "base/base.html" %}


{% block panel_itle %}
    <div class="panel-heading">
        <h3 class="panel-title">主机管理</h3>
    </div>
{% endblock panel_itle %}

{% block table %}
    <!--表格 工具栏结束-->
    <div class="row table-toolbar">
        <div class="col-md-9">
            <div class="input-group">
                <td id="Search_ip">
                    <input type="text" class="form-control" placeholder="Search for ip...">
                    <span class="input-group-btn">
                        <button class="btn btn-default" type="button">Go!</button>
                    </span>
                </td>
                <td id="Search_type">
                    <input type="text" class="form-control" placeholder="Search for type...">
                    <span class="input-group-btn">
                        <button class="btn btn-default" type="button">Go!</button>
                    </span>
                </td>
                <td>
                    <input type="Search_idc" class="form-control" placeholder="Search for idc...">
                    <span class="input-group-btn">
                        <button class="btn btn-default" type="button">Go!</button>
                    </span>
                </td>
            </div>
        </div><!-- /.col-lg-6 -->
        {% block add_host %}
        {% endblock add_host %}
    </div>
    <table class="table table-striped table-bordered">
        <thead>
        <tr>
            <th>id</th>
            <th>主机名</th>
            <th>内网iP</th>
            <th>外网iP</th>
            <th>类型</th>
            <th>机房</th>
            <th>管理人员</th>
            <th>操作</th>
        </tr>
        </thead>
        <tbody id="tb">
        {% for host in host_list %}
            <tr nid="{{ host.id }}">
                {#                <td>{{ forloop.counter }}</td>#}
                <td na="nid">{{ host.id }}</td>
                <td na="host_name">{{ host.host_name }}</td>
                <td>{{ host.in_ip }}</td>
                <td>{{ host.out_ip }}</td>
                <td>{{ host.Host_group }}</td>
                <td>{{ host.idc }}</td>
                <td>{{ host.user }}</td>
                <td>
                    <a href="#">
                        <button class="btn btn-info btn-sm">
                            <i class="fa  fa-fw" aria-hidden="true"></i>连接
                        </button>
                    </a>
                    <a href="#">
                        <button class="btn btn-info btn-sm">
                            <i class="fa fa-pencil fa-fw" aria-hidden="true"></i>监控
                        </button>
                    </a>
                    {% block operation %}
                    {% endblock operation %}
                </td>
            </tr>
        {% endfor %}

        </tbody>
    </table>
{% endblock table %}


{% block model %}
    <div class="modal fade" id="delModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span
                            aria-hidden="true">&times;</span></button>
                    <h4 class="modal-title" id="myModalLabel">删除主机</h4>
                </div>
                <div class="modal-body">
                    <form id="fm" class="form-horizontal">
                        <input type="text" class="ni" name="nid" style="display: none"/>

                        <div class="form-group">
                            <label for="username" class="col-sm-2 control-label">姓名</label>
                            <div class="col-sm-10">
                                <input type="text" class="form-control" readOnly="true" name="user" placeholder="姓名">
                            </div>
                        </div>
                    </form>
                </div>
                <div class="modal-footer">
                    <span id="errorMsg" style="color: red;"></span>
                    <button type="button" class="btn btn-default" data-dismiss="modal">取消</button>
                    <button type="button" class="btn btn-primary" id="delConfirm">删除</button>
                </div>
            </div>
        </div>
    </div>
{% endblock model %}

Mytest/templates/login.html
<!DOCTYPE html>
<html lang="zh-CN">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- 上述3个meta标签*必须*放在最前面，任何其他内容都*必须*跟随其后！ -->
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="../../favicon.ico">

    <title>Signin Template for Bootstrap</title>
    <link href="/static/Bootstrap_files/bootstrap.min.css" rel="stylesheet">

  </head>

  <body>

    <div class="container">

      <form class="form-signin">
        <h2 class="form-signin-heading">Please sign in</h2>
        <label for="inputEmail" class="sr-only">Email address</label>
        <input type="email" id="inputEmail" class="form-control" placeholder="Email address" required autofocus>
        <label for="inputPassword" class="sr-only">Password</label>
        <input type="password" id="inputPassword" class="form-control" placeholder="Password" required>
        <div class="checkbox">
          <label>
            <input type="checkbox" value="remember-me"> Remember me
          </label>
        </div>
        <button class="btn btn-lg btn-primary btn-block" type="submit">Sign in</button>
      </form>

    </div> <!-- /container -->

  </body>
</html>